package com.thmub.newbook.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.thmub.newbook.bean.BookSourceBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_SOURCE_BEAN".
*/
public class BookSourceBeanDao extends AbstractDao<BookSourceBean, String> {

    public static final String TABLENAME = "BOOK_SOURCE_BEAN";

    /**
     * Properties of entity BookSourceBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property RootLink = new Property(0, String.class, "rootLink", true, "ROOT_LINK");
        public final static Property SourceName = new Property(1, String.class, "sourceName", false, "SOURCE_NAME");
        public final static Property SourceType = new Property(2, String.class, "sourceType", false, "SOURCE_TYPE");
        public final static Property EncodeType = new Property(3, String.class, "encodeType", false, "ENCODE_TYPE");
        public final static Property SearchLink = new Property(4, String.class, "searchLink", false, "SEARCH_LINK");
        public final static Property RuleSearchBooks = new Property(5, String.class, "ruleSearchBooks", false, "RULE_SEARCH_BOOKS");
        public final static Property RuleSearchTitle = new Property(6, String.class, "ruleSearchTitle", false, "RULE_SEARCH_TITLE");
        public final static Property RuleSearchAuthor = new Property(7, String.class, "ruleSearchAuthor", false, "RULE_SEARCH_AUTHOR");
        public final static Property RuleSearchDesc = new Property(8, String.class, "ruleSearchDesc", false, "RULE_SEARCH_DESC");
        public final static Property RuleSearchCover = new Property(9, String.class, "ruleSearchCover", false, "RULE_SEARCH_COVER");
        public final static Property RuleSearchLink = new Property(10, String.class, "ruleSearchLink", false, "RULE_SEARCH_LINK");
        public final static Property RuleDetailBook = new Property(11, String.class, "ruleDetailBook", false, "RULE_DETAIL_BOOK");
        public final static Property RuleDetailTitle = new Property(12, String.class, "ruleDetailTitle", false, "RULE_DETAIL_TITLE");
        public final static Property RuleDetailAuthor = new Property(13, String.class, "ruleDetailAuthor", false, "RULE_DETAIL_AUTHOR");
        public final static Property RuleDetailDesc = new Property(14, String.class, "ruleDetailDesc", false, "RULE_DETAIL_DESC");
        public final static Property RuleDetailCover = new Property(15, String.class, "ruleDetailCover", false, "RULE_DETAIL_COVER");
        public final static Property RuleFindLink = new Property(16, String.class, "ruleFindLink", false, "RULE_FIND_LINK");
        public final static Property RuleCatalogLink = new Property(17, String.class, "ruleCatalogLink", false, "RULE_CATALOG_LINK");
        public final static Property RuleChapters = new Property(18, String.class, "ruleChapters", false, "RULE_CHAPTERS");
        public final static Property RuleChapterLink = new Property(19, String.class, "ruleChapterLink", false, "RULE_CHAPTER_LINK");
        public final static Property RuleChapterTitle = new Property(20, String.class, "ruleChapterTitle", false, "RULE_CHAPTER_TITLE");
        public final static Property RuleChapterContent = new Property(21, String.class, "ruleChapterContent", false, "RULE_CHAPTER_CONTENT");
        public final static Property OrderNumber = new Property(22, int.class, "orderNumber", false, "ORDER_NUMBER");
        public final static Property Weight = new Property(23, int.class, "weight", false, "WEIGHT");
        public final static Property IsSelected = new Property(24, boolean.class, "isSelected", false, "IS_SELECTED");
    }


    public BookSourceBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookSourceBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_SOURCE_BEAN\" (" + //
                "\"ROOT_LINK\" TEXT PRIMARY KEY NOT NULL ," + // 0: rootLink
                "\"SOURCE_NAME\" TEXT," + // 1: sourceName
                "\"SOURCE_TYPE\" TEXT," + // 2: sourceType
                "\"ENCODE_TYPE\" TEXT," + // 3: encodeType
                "\"SEARCH_LINK\" TEXT," + // 4: searchLink
                "\"RULE_SEARCH_BOOKS\" TEXT," + // 5: ruleSearchBooks
                "\"RULE_SEARCH_TITLE\" TEXT," + // 6: ruleSearchTitle
                "\"RULE_SEARCH_AUTHOR\" TEXT," + // 7: ruleSearchAuthor
                "\"RULE_SEARCH_DESC\" TEXT," + // 8: ruleSearchDesc
                "\"RULE_SEARCH_COVER\" TEXT," + // 9: ruleSearchCover
                "\"RULE_SEARCH_LINK\" TEXT," + // 10: ruleSearchLink
                "\"RULE_DETAIL_BOOK\" TEXT," + // 11: ruleDetailBook
                "\"RULE_DETAIL_TITLE\" TEXT," + // 12: ruleDetailTitle
                "\"RULE_DETAIL_AUTHOR\" TEXT," + // 13: ruleDetailAuthor
                "\"RULE_DETAIL_DESC\" TEXT," + // 14: ruleDetailDesc
                "\"RULE_DETAIL_COVER\" TEXT," + // 15: ruleDetailCover
                "\"RULE_FIND_LINK\" TEXT," + // 16: ruleFindLink
                "\"RULE_CATALOG_LINK\" TEXT," + // 17: ruleCatalogLink
                "\"RULE_CHAPTERS\" TEXT," + // 18: ruleChapters
                "\"RULE_CHAPTER_LINK\" TEXT," + // 19: ruleChapterLink
                "\"RULE_CHAPTER_TITLE\" TEXT," + // 20: ruleChapterTitle
                "\"RULE_CHAPTER_CONTENT\" TEXT," + // 21: ruleChapterContent
                "\"ORDER_NUMBER\" INTEGER NOT NULL ," + // 22: orderNumber
                "\"WEIGHT\" INTEGER NOT NULL ," + // 23: weight
                "\"IS_SELECTED\" INTEGER NOT NULL );"); // 24: isSelected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_SOURCE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookSourceBean entity) {
        stmt.clearBindings();
 
        String rootLink = entity.getRootLink();
        if (rootLink != null) {
            stmt.bindString(1, rootLink);
        }
 
        String sourceName = entity.getSourceName();
        if (sourceName != null) {
            stmt.bindString(2, sourceName);
        }
 
        String sourceType = entity.getSourceType();
        if (sourceType != null) {
            stmt.bindString(3, sourceType);
        }
 
        String encodeType = entity.getEncodeType();
        if (encodeType != null) {
            stmt.bindString(4, encodeType);
        }
 
        String searchLink = entity.getSearchLink();
        if (searchLink != null) {
            stmt.bindString(5, searchLink);
        }
 
        String ruleSearchBooks = entity.getRuleSearchBooks();
        if (ruleSearchBooks != null) {
            stmt.bindString(6, ruleSearchBooks);
        }
 
        String ruleSearchTitle = entity.getRuleSearchTitle();
        if (ruleSearchTitle != null) {
            stmt.bindString(7, ruleSearchTitle);
        }
 
        String ruleSearchAuthor = entity.getRuleSearchAuthor();
        if (ruleSearchAuthor != null) {
            stmt.bindString(8, ruleSearchAuthor);
        }
 
        String ruleSearchDesc = entity.getRuleSearchDesc();
        if (ruleSearchDesc != null) {
            stmt.bindString(9, ruleSearchDesc);
        }
 
        String ruleSearchCover = entity.getRuleSearchCover();
        if (ruleSearchCover != null) {
            stmt.bindString(10, ruleSearchCover);
        }
 
        String ruleSearchLink = entity.getRuleSearchLink();
        if (ruleSearchLink != null) {
            stmt.bindString(11, ruleSearchLink);
        }
 
        String ruleDetailBook = entity.getRuleDetailBook();
        if (ruleDetailBook != null) {
            stmt.bindString(12, ruleDetailBook);
        }
 
        String ruleDetailTitle = entity.getRuleDetailTitle();
        if (ruleDetailTitle != null) {
            stmt.bindString(13, ruleDetailTitle);
        }
 
        String ruleDetailAuthor = entity.getRuleDetailAuthor();
        if (ruleDetailAuthor != null) {
            stmt.bindString(14, ruleDetailAuthor);
        }
 
        String ruleDetailDesc = entity.getRuleDetailDesc();
        if (ruleDetailDesc != null) {
            stmt.bindString(15, ruleDetailDesc);
        }
 
        String ruleDetailCover = entity.getRuleDetailCover();
        if (ruleDetailCover != null) {
            stmt.bindString(16, ruleDetailCover);
        }
 
        String ruleFindLink = entity.getRuleFindLink();
        if (ruleFindLink != null) {
            stmt.bindString(17, ruleFindLink);
        }
 
        String ruleCatalogLink = entity.getRuleCatalogLink();
        if (ruleCatalogLink != null) {
            stmt.bindString(18, ruleCatalogLink);
        }
 
        String ruleChapters = entity.getRuleChapters();
        if (ruleChapters != null) {
            stmt.bindString(19, ruleChapters);
        }
 
        String ruleChapterLink = entity.getRuleChapterLink();
        if (ruleChapterLink != null) {
            stmt.bindString(20, ruleChapterLink);
        }
 
        String ruleChapterTitle = entity.getRuleChapterTitle();
        if (ruleChapterTitle != null) {
            stmt.bindString(21, ruleChapterTitle);
        }
 
        String ruleChapterContent = entity.getRuleChapterContent();
        if (ruleChapterContent != null) {
            stmt.bindString(22, ruleChapterContent);
        }
        stmt.bindLong(23, entity.getOrderNumber());
        stmt.bindLong(24, entity.getWeight());
        stmt.bindLong(25, entity.getIsSelected() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookSourceBean entity) {
        stmt.clearBindings();
 
        String rootLink = entity.getRootLink();
        if (rootLink != null) {
            stmt.bindString(1, rootLink);
        }
 
        String sourceName = entity.getSourceName();
        if (sourceName != null) {
            stmt.bindString(2, sourceName);
        }
 
        String sourceType = entity.getSourceType();
        if (sourceType != null) {
            stmt.bindString(3, sourceType);
        }
 
        String encodeType = entity.getEncodeType();
        if (encodeType != null) {
            stmt.bindString(4, encodeType);
        }
 
        String searchLink = entity.getSearchLink();
        if (searchLink != null) {
            stmt.bindString(5, searchLink);
        }
 
        String ruleSearchBooks = entity.getRuleSearchBooks();
        if (ruleSearchBooks != null) {
            stmt.bindString(6, ruleSearchBooks);
        }
 
        String ruleSearchTitle = entity.getRuleSearchTitle();
        if (ruleSearchTitle != null) {
            stmt.bindString(7, ruleSearchTitle);
        }
 
        String ruleSearchAuthor = entity.getRuleSearchAuthor();
        if (ruleSearchAuthor != null) {
            stmt.bindString(8, ruleSearchAuthor);
        }
 
        String ruleSearchDesc = entity.getRuleSearchDesc();
        if (ruleSearchDesc != null) {
            stmt.bindString(9, ruleSearchDesc);
        }
 
        String ruleSearchCover = entity.getRuleSearchCover();
        if (ruleSearchCover != null) {
            stmt.bindString(10, ruleSearchCover);
        }
 
        String ruleSearchLink = entity.getRuleSearchLink();
        if (ruleSearchLink != null) {
            stmt.bindString(11, ruleSearchLink);
        }
 
        String ruleDetailBook = entity.getRuleDetailBook();
        if (ruleDetailBook != null) {
            stmt.bindString(12, ruleDetailBook);
        }
 
        String ruleDetailTitle = entity.getRuleDetailTitle();
        if (ruleDetailTitle != null) {
            stmt.bindString(13, ruleDetailTitle);
        }
 
        String ruleDetailAuthor = entity.getRuleDetailAuthor();
        if (ruleDetailAuthor != null) {
            stmt.bindString(14, ruleDetailAuthor);
        }
 
        String ruleDetailDesc = entity.getRuleDetailDesc();
        if (ruleDetailDesc != null) {
            stmt.bindString(15, ruleDetailDesc);
        }
 
        String ruleDetailCover = entity.getRuleDetailCover();
        if (ruleDetailCover != null) {
            stmt.bindString(16, ruleDetailCover);
        }
 
        String ruleFindLink = entity.getRuleFindLink();
        if (ruleFindLink != null) {
            stmt.bindString(17, ruleFindLink);
        }
 
        String ruleCatalogLink = entity.getRuleCatalogLink();
        if (ruleCatalogLink != null) {
            stmt.bindString(18, ruleCatalogLink);
        }
 
        String ruleChapters = entity.getRuleChapters();
        if (ruleChapters != null) {
            stmt.bindString(19, ruleChapters);
        }
 
        String ruleChapterLink = entity.getRuleChapterLink();
        if (ruleChapterLink != null) {
            stmt.bindString(20, ruleChapterLink);
        }
 
        String ruleChapterTitle = entity.getRuleChapterTitle();
        if (ruleChapterTitle != null) {
            stmt.bindString(21, ruleChapterTitle);
        }
 
        String ruleChapterContent = entity.getRuleChapterContent();
        if (ruleChapterContent != null) {
            stmt.bindString(22, ruleChapterContent);
        }
        stmt.bindLong(23, entity.getOrderNumber());
        stmt.bindLong(24, entity.getWeight());
        stmt.bindLong(25, entity.getIsSelected() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookSourceBean readEntity(Cursor cursor, int offset) {
        BookSourceBean entity = new BookSourceBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // rootLink
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sourceName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sourceType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // encodeType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // searchLink
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ruleSearchBooks
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ruleSearchTitle
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ruleSearchAuthor
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ruleSearchDesc
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ruleSearchCover
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ruleSearchLink
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ruleDetailBook
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // ruleDetailTitle
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // ruleDetailAuthor
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // ruleDetailDesc
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // ruleDetailCover
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // ruleFindLink
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // ruleCatalogLink
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // ruleChapters
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // ruleChapterLink
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // ruleChapterTitle
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // ruleChapterContent
            cursor.getInt(offset + 22), // orderNumber
            cursor.getInt(offset + 23), // weight
            cursor.getShort(offset + 24) != 0 // isSelected
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookSourceBean entity, int offset) {
        entity.setRootLink(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSourceName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSourceType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEncodeType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSearchLink(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRuleSearchBooks(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRuleSearchTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setRuleSearchAuthor(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRuleSearchDesc(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRuleSearchCover(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRuleSearchLink(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setRuleDetailBook(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRuleDetailTitle(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRuleDetailAuthor(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setRuleDetailDesc(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setRuleDetailCover(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRuleFindLink(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setRuleCatalogLink(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRuleChapters(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setRuleChapterLink(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setRuleChapterTitle(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setRuleChapterContent(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setOrderNumber(cursor.getInt(offset + 22));
        entity.setWeight(cursor.getInt(offset + 23));
        entity.setIsSelected(cursor.getShort(offset + 24) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookSourceBean entity, long rowId) {
        return entity.getRootLink();
    }
    
    @Override
    public String getKey(BookSourceBean entity) {
        if(entity != null) {
            return entity.getRootLink();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookSourceBean entity) {
        return entity.getRootLink() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
