package com.thmub.newbook.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thmub.newbook.bean.BookChapterBean;
import com.thmub.newbook.bean.BookMarkBean;
import com.thmub.newbook.bean.BookSourceBean;
import com.thmub.newbook.bean.ShelfBookBean;

import com.thmub.newbook.model.dao.BookChapterBeanDao;
import com.thmub.newbook.model.dao.BookMarkBeanDao;
import com.thmub.newbook.model.dao.BookSourceBeanDao;
import com.thmub.newbook.model.dao.ShelfBookBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookChapterBeanDaoConfig;
    private final DaoConfig bookMarkBeanDaoConfig;
    private final DaoConfig bookSourceBeanDaoConfig;
    private final DaoConfig shelfBookBeanDaoConfig;

    private final BookChapterBeanDao bookChapterBeanDao;
    private final BookMarkBeanDao bookMarkBeanDao;
    private final BookSourceBeanDao bookSourceBeanDao;
    private final ShelfBookBeanDao shelfBookBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookChapterBeanDaoConfig = daoConfigMap.get(BookChapterBeanDao.class).clone();
        bookChapterBeanDaoConfig.initIdentityScope(type);

        bookMarkBeanDaoConfig = daoConfigMap.get(BookMarkBeanDao.class).clone();
        bookMarkBeanDaoConfig.initIdentityScope(type);

        bookSourceBeanDaoConfig = daoConfigMap.get(BookSourceBeanDao.class).clone();
        bookSourceBeanDaoConfig.initIdentityScope(type);

        shelfBookBeanDaoConfig = daoConfigMap.get(ShelfBookBeanDao.class).clone();
        shelfBookBeanDaoConfig.initIdentityScope(type);

        bookChapterBeanDao = new BookChapterBeanDao(bookChapterBeanDaoConfig, this);
        bookMarkBeanDao = new BookMarkBeanDao(bookMarkBeanDaoConfig, this);
        bookSourceBeanDao = new BookSourceBeanDao(bookSourceBeanDaoConfig, this);
        shelfBookBeanDao = new ShelfBookBeanDao(shelfBookBeanDaoConfig, this);

        registerDao(BookChapterBean.class, bookChapterBeanDao);
        registerDao(BookMarkBean.class, bookMarkBeanDao);
        registerDao(BookSourceBean.class, bookSourceBeanDao);
        registerDao(ShelfBookBean.class, shelfBookBeanDao);
    }
    
    public void clear() {
        bookChapterBeanDaoConfig.clearIdentityScope();
        bookMarkBeanDaoConfig.clearIdentityScope();
        bookSourceBeanDaoConfig.clearIdentityScope();
        shelfBookBeanDaoConfig.clearIdentityScope();
    }

    public BookChapterBeanDao getBookChapterBeanDao() {
        return bookChapterBeanDao;
    }

    public BookMarkBeanDao getBookMarkBeanDao() {
        return bookMarkBeanDao;
    }

    public BookSourceBeanDao getBookSourceBeanDao() {
        return bookSourceBeanDao;
    }

    public ShelfBookBeanDao getShelfBookBeanDao() {
        return shelfBookBeanDao;
    }

}
