package com.thmub.newbook.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thmub.newbook.bean.BookSourceBean;
import com.thmub.newbook.bean.BookChapterBean;
import com.thmub.newbook.bean.ShelfBookBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookSourceBeanDaoConfig;
    private final DaoConfig bookChapterBeanDaoConfig;
    private final DaoConfig shelfBookBeanDaoConfig;

    private final BookSourceBeanDao bookSourceBeanDao;
    private final BookChapterBeanDao bookChapterBeanDao;
    private final ShelfBookBeanDao shelfBookBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookSourceBeanDaoConfig = daoConfigMap.get(BookSourceBeanDao.class).clone();
        bookSourceBeanDaoConfig.initIdentityScope(type);

        bookChapterBeanDaoConfig = daoConfigMap.get(BookChapterBeanDao.class).clone();
        bookChapterBeanDaoConfig.initIdentityScope(type);

        shelfBookBeanDaoConfig = daoConfigMap.get(ShelfBookBeanDao.class).clone();
        shelfBookBeanDaoConfig.initIdentityScope(type);

        bookSourceBeanDao = new BookSourceBeanDao(bookSourceBeanDaoConfig, this);
        bookChapterBeanDao = new BookChapterBeanDao(bookChapterBeanDaoConfig, this);
        shelfBookBeanDao = new ShelfBookBeanDao(shelfBookBeanDaoConfig, this);

        registerDao(BookSourceBean.class, bookSourceBeanDao);
        registerDao(BookChapterBean.class, bookChapterBeanDao);
        registerDao(ShelfBookBean.class, shelfBookBeanDao);
    }
    
    public void clear() {
        bookSourceBeanDaoConfig.clearIdentityScope();
        bookChapterBeanDaoConfig.clearIdentityScope();
        shelfBookBeanDaoConfig.clearIdentityScope();
    }

    public BookSourceBeanDao getBookSourceBeanDao() {
        return bookSourceBeanDao;
    }

    public BookChapterBeanDao getBookChapterBeanDao() {
        return bookChapterBeanDao;
    }

    public ShelfBookBeanDao getShelfBookBeanDao() {
        return shelfBookBeanDao;
    }

}
